# Generated by Django 6.0.7 on 2026-07-16 02:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_group_task_group"),
        ("todo", "0002_task_favorite"),
    ]

    operations = []
