# Generated by Django 6.0.6 on 2026-07-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
